- .gitignore
- package-lock.json
- package.json
- src/app.js
- src/helper/utils.js
- src/middlewares/index.js
- src/restful/controllers/OpportunitiesControllers.js
- src/restful/controllers/authControllers.js
- src/restful/controllers/chatControllers.js
- src/restful/routes/authRouters.js
- src/restful/routes/chatRouters.js
- src/restful/routes/index.js
- src/restful/routes/opportunitiesRouters.js
**What does this PR do?**
- Set up a Node.js project with essential tools such as Linter, Babel, Git, and an MVC folder structure.
- Configured Firebase Admin(NodeJS) and established Firebase Firestore database.
- Implemented authentication middleware to consistently Authenticate incoming requests with an authentication token validation.
- Developed endpoints for fetching the current user profile and updating it.
- Added an endpoint to retrieve opportunities.
- Created endpoints for sending and receiving messages, along with listing all users.
**How should this be manually tested?**
1. Clone this repository and switch to `ft-add-firebase`
2. Install all required dependencies `npm install`
3. run `npm run dev`
> Firebase Integration

- src/restful/controllers/OpportunitiesControllers.js
- src/restful/routes/opportunitiesRouters.js
> opportuniteschange

- src/restful/controllers/opportunitiesController.js
- src/restful/routes/opportunitiesRouter.js
> Update opportunity keys

- package-lock.json
- package.json
- src/helper/mailHelper.js
- src/middlewares/index.js
- src/restful/controllers/authController.js
- src/restful/routes/authRouter.js
- src/restful/routes/authRouters.js
- src/services/templates/SendOtpEmail.js
- src/services/templates/SendPasswordReset.js
**What does this PR do?**
1. Add a reset password functionality
**How should this be manually tested?**
1. Clone this repository and switch to `ft-reset-password`
2. Install all required dependencies `npm install`
3. npm run dev
4. send a post request to this link `/v1/auth/reset`
5. use this as a request body 
`{`
`   "email": "your email"`
`}
`
5. screenshots
> Ft reset password

- src/restful/controllers/authController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/routes/authRouter.js
- implement caching techniques to get all opportunities and get a profile
-  Improve the get profile endpoint by using the current role instead of looping through all role
> Feature use Caching technique

- src/middleware/index.js
- src/restful/controllers/authController.js
- src/restful/routes/authRouter.js
- src/restful/routes/chatRouter.js
- Refactors the signup step into one function
- Stores users in a single collection
- Adds route to get all users public information
- Renamed routes to utilise user instead of profile
> feat: added users route and unified sign up

- src/restful/controllers/opportunitiesController.js
> changed how the delete endpoint works

- src/restful/controllers/authController.js
> Handle invalid emails on user signup

- src/restful/controllers/authController.js
1. In case the same email before in OTP collection the second verification will fail with an invalid verification code
2.  Describe your changes
> Bug Fix(Error during verification):

- .firebaserc
- .gitignore
- src/helper/allowedRole.js
- src/index.js
- src/restful/controllers/adminController.js
- src/restful/controllers/authController.js
- src/restful/routes/adminRouter.js
- src/restful/routes/index.js
- Allow the admin user to create another admin user
- User with an email from .env variable will have admin capability by default 
- create and protect a middleware that will check if the user is an admin before proceeding with admin features
> Add admin capability

- src/restful/controllers/applicationsController.js
- src/restful/controllers/contractController.js
- src/restful/controllers/opportunitiesController.js
> 83 add compensation field

- src/restful/controllers/applicationsController.js
- src/restful/controllers/opportunitiesController.js
> changed name of brand to client

- src/restful/controllers/adminController.js
- src/restful/routes/adminRouter.js
> Allow admin to delete user

- src/restful/controllers/applicationsController.js
- src/restful/controllers/contractController.js
- src/restful/controllers/opportunitiesController.js
> changed name back to original

- src/restful/controllers/authController.js
- src/restful/routes/authRouter.js
- Implemented the ability for users to update their username and email address.
- Enabling user to change their password securely.
> User Profile Settings

- src/restful/controllers/opportunitiesController.js
> updated error handling

- src/restful/controllers/authController.js
- src/restful/routes/authRouter.js
- Removes the username endpoint and function as we are now dropping this feature
> feat: remove username

- src/restful/controllers/applicationsController.js
- src/restful/controllers/chatController.js
- src/restful/routes/chatRouter.js
> reworked chat controller and routes

- src/restful/controllers/opportunitiesController.js
- Throws error for invalid opportunity types
- Adds a status code for posting an opportunity
> tweak: throw error message

- src/restful/controllers/authController.js
- src/restful/routes/authRouter.js
> added check

- src/restful/controllers/authController.js
This pull request addresses the issue where a user account could still be created even when some steps in the signup process fail. Specifically, it ensures that if any part of the signup process fails (such as sending a verification email), the created user account will be deleted to maintain data consistency.
> Delete User in Case of Signup Failure

- src/restful/controllers/opportunitiesController.js
> addded pagination

- src/restful/controllers/adminController.js
#132 
This should remove our custom approach and replace it with firebase's where applicable
> Use firebase default property "disabled"

- .github/pull_request_template.md
- package.json
- src/helper/allowedRole.js
- src/helper/apiCallLog.js
- src/restful/controllers/adminController.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/authController.js
- src/restful/controllers/chatController.js
- src/restful/controllers/contractController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/routes/adminRouter.js
- src/restful/routes/applicationsRouter.js
- src/restful/routes/authRouter.js
- src/restful/routes/chatRouter.js
> added new endpoints

- package-lock.json
- package.json
- src/restful/controllers/authController.js
- src/restful/routes/chatRouter.js
> 122 signup validation

- src/restful/controllers/applicationsController.js
create room by paring two user ids
> create room by paring two user ids

- src/index.js
> feat: update index.js

- src/index.js
- src/restful/controllers/authController.js
- src/restful/routes/chatRouter.js
- Remove chat routes that are no longer needed because we're connecting directly to the API
- Conditionally use schema depending on roles
> fix: schema validation

- src/restful/controllers/opportunitiesController.js
- src/restful/routes/applicationsRouter.js
- Fixed bug in opportunities controller that was preventing POSTING opportunities
- Changed PUT to PATCH in applications router
> fix: opportunities and applications router/controller

- .github/workflows/prettier.yml
- package.json
- src/restful/controllers/adminController.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/authController.js
- src/restful/controllers/chatController.js
- src/restful/controllers/contractController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/routes/applicationsRouter.js
- src/restful/routes/authRouter.js
- src/restful/routes/chatRouter.js
- Adds gh workflow actions to make sure all code is formatted the same
- Removes validation for updating profile to remove errors
> tweak: various

- src/restful/controllers/opportunitiesController.js
Adds a handler for the optional prompt field
Closes #135
> feat: add prompt field to opportunity

- package-lock.json
- package.json
- src/restful/controllers/adminController.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/authController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/controllers/paymentController.js
- src/restful/routes/adminRouter.js
- src/restful/routes/applicationsRouter.js
- src/restful/routes/authRouter.js
- src/restful/routes/index.js
- src/restful/routes/paymentRouter.js
Adds stripe integration
Closes #2
> feat: stripe integration

- src/restful/controllers/authController.js
- src/restful/routes/chatRouter.js
It was not working well when i pulled changes from the main
> Update updateUser endpoint to handle profile_meta as an object

- src/restful/controllers/opportunitiesController.js
Archived opportunities should not be displayed
> Fix Archived opportunities Issue

- src/restful/controllers/adminController.js
- src/restful/controllers/authController.js
- src/restful/routes/adminRouter.js
Develop an Endpoint for Displaying the Aggregates on the Admin Dashboard
>  Aggregates on Admin Dashboard

- src/restful/controllers/opportunitiesController.js
> add image to opportunity

- src/restful/controllers/authController.js
- src/restful/controllers/paymentController.js
- src/restful/routes/authRouter.js
> updated feat/plus backend

- src/restful/controllers/authController.js
- src/restful/controllers/opportunitiesController.js
> added brand name

- src/restful/controllers/paymentController.js
- src/restful/routes/paymentRouter.js
Adds a route that checks to see if the status of a transaction is complete and sets the users subscription value to true
> feat: adds a route to subscribe user

- src/restful/controllers/applicationsController.js
- src/restful/controllers/chatController.js
Returns room id when an application is accepted
Closes #163
> feat: return room id when application is accepted

- src/index.js
- src/restful/controllers/authController.js
Separate the storage bucket for development and production
> Separate the storage bucket for development and production

- src/restful/controllers/paymentController.js
- src/restful/routes/paymentRouter.js
> added cancel endpoint

- src/restful/controllers/paymentController.js
> Store subscription

- src/restful/controllers/authController.js
Remove is activated field as it is no longer needed
Closes #177
> Remove is activated field

- .firebaserc
- package-lock.json
- package.json
- src/helper/allowedRole.js
- src/helper/mailHelper.js
- src/index.js
- src/restful/controllers/authController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/routes/adminRouter.js
- src/services/templates/SendOtpEmail.js
- src/services/templates/SendPasswordReset.js
Uses template strings to reduce amount of variables in the env file
> refactor: reduce amount of env variables

- src/restful/controllers/adminController.js
> Attach name and logo to the company on each user

- src/restful/controllers/applicationsController.js
- src/restful/controllers/chatController.js
- src/restful/routes/chatRouter.js
> updated chat router

- src/restful/controllers/adminController.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/authController.js
- src/restful/controllers/chatController.js
- src/restful/controllers/contractController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/controllers/paymentController.js
- src/restful/routes/adminRouter.js
- src/restful/routes/applicationsRouter.js
- src/restful/routes/authRouter.js
- src/restful/routes/contractRouter.js
- src/restful/routes/opportunitiesRouter.js
- src/restful/routes/paymentRouter.js
Updates the codebase to use camel case as there was a mixture of pascal case and camel case
> refactor: update codebase to use camel case accross the board

- src/restful/controllers/adminController.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/authController.js
- src/restful/controllers/opportunitiesController.js
> tweak: change profileImage and imageUrl to profilePhoto

- src/restful/controllers/applicationsController.js
- src/restful/controllers/opportunitiesController.js
-Fix application popup issue
-Fetch the user profile with referencing the image -Fix variable missmatch issues
-Fix proposal issue due to missmatch in variables
> Reference the image whenever it is used

- src/restful/controllers/authController.js
> updated branch

- src/restful/controllers/applicationsController.js
A user cannot apply to the same opportunity twice. #215
> Prevent user to apply twice

- src/helper/sendNotification.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/notificationController.js
- src/restful/routes/notificationRouter.js
- src/services/templates/SendReceiveApllicationEmail.js
- src/services/templates/SendRejectEmail.js
Implemented the functionalities from  #85
> Notifications Update

- src/restful/controllers/adminController.js
- Stores delete functions into Promise.all
- Updates all error messages to console messages rather than the entire error object
> update admin delete user

- src/middleware/index.js
Before authorizing the user, check if they have been disabled by the system administrator.
> Prevent disabled users from logging in

- src/restful/controllers/adminController.js
-Super admin cannot be deleted
-Admin cannot delete another admin
#231
> Improve admin and supper admin capabilities

- src/restful/controllers/applicationsController.js
> Add pagination for retrieving applications by opportunity ID

- src/restful/controllers/applicationsController.js
> Fix you have already applied to this opportunities issue

- package-lock.json
- package.json
- src/helper/checkSubscribedUser.js
- src/helper/cronjob.js
- src/index.js
- src/restful/controllers/adminController.js
- src/restful/controllers/applicationsController.js
- src/restful/controllers/opportunitiesController.js
- src/restful/routes/adminRouter.js
By the end of each month, all unsubscribed users will have their count of opportunities applied for or posted reset to 0
> Automatically reset all users' credits every month

- .firebaserc
- firebase.json
- functions/.gitignore
- functions/firebase-debug.log
- functions/index.js
- functions/package-lock.json
- functions/package.json
- functions/ui-debug.log
- package-lock.json
- package.json
- src/helper/checkSubscribedUser.js
- src/index.js
- src/restful/controllers/authController.js
- src/restful/controllers/paymentController.js
- src/restful/routes/paymentRouter.js
- ui-debug.log
- Adds a cloud function `stripeEvent` that is fired by the stripe event: `customer.subscription.deleted` this function removes the `subscriptionId` from the user with a `subscriptionId` that matched the `subscriptionId` passed in the stripe object
Closes #238
> feat: remove subscription id when subscription is deleted

- src/helper/cronjob.js
- src/restful/controllers/opportunitiesController.js
It will run the task every day at midnight and archive an opportunity if its deadline has passed
#239
> Archive an opportunity if its deadline has passed

- .firebaserc
- functions/README.md
- functions/index.js
- src/index.js
- src/restful/controllers/paymentController.js
- Stops user doc from being updated on subscription cancelled event
- Adds a README.md to the functions dir
- Adds feature to set user claims for user when a users subscription is deleted
> tweak: stripeEvent function and paymentsController

- src/restful/controllers/opportunitiesController.js
> Fix pagiation to be consistent

- src/restful/controllers/opportunitiesController.js
> Remove next after id
